create table employees(
	id serial primary key,
	employee_name varchar(50) not null
);

select * from employees

insert into employees (employee_name)
values ('James Moore'),
	   ('Rita Bennett'),
	   ('Margaret Owens'),
	   ('Margaret Daniels'),
	   ('Melvin Reed'),
	   ('Christina Ingram'),
	   ('Joseph Curtis'),
	   ('Harry Riley'),
	   ('Lawrence Young'),
	   ('Lucille Hanson'),
	   ('Linda West'),
	   ('Jonathan Martinez'),
	   ('Roberto Hayes'),
	   ('Edward Jones'),
	   ('Jesse Bryant'),
	   ('Daniel Reyes'),
	   ('William Lane'),
	   ('Mark Smith'),
	   ('Jose Lee'),
	   ('Daniel Wells'),
	   ('John Price'),
	   ('Michael Lewis'),
	   ('Robert Garcia'),
	   ('Andrea Miller'),
	   ('Katrina Smith'),
	   ('Holly Boyd'),
	   ('Alan Carter'),
	   ('Ann Sanders'),
	   ('James Malone'),
	   ('Caroline Crawford'),
	   ('Nathan Moss'),
	   ('Frances Parker'),
	   ('Joseph Gregory'),
	   ('Dorothy Berry'),
	   ('Michael Townsend'),
	   ('Claudia Brown'),
	   ('Joseph White'),
	   ('Lisa Banks'),
	   ('Jack Brown'),
	   ('Lillie Brown'),
	   ('James Lewis'),
	   ('Debra Taylor'),
	   ('Stacey Barnett'),
	   ('Lonnie Guerrero'),
	   ('Mary Jackson'),
	   ('Joseph Stewart'),
	   ('James Miller'),
	   ('Mark Thomas'),
	   ('Wayne Daniels'),
	   ('Michael Johnson'),
	   ('Danny Thornton'),
	   ('Sheila Henry'),
	   ('Alice Bell'),
	   ('Jeffery Reed'),
	   ('Robert Sullivan'),
	   ('Carolyn Moran'),
	   ('Lucille Smith'),
	   ('Constance Lewis'),
	   ('Jonathan Burns'),
	   ('Mary Medina'),
	   ('Mary Cross'),
	   ('John Nguyen'),
	   ('Robert Ellis'),
	   ('Mildred Austin'),
	   ('Brent Kelley'),
	   ('Barry Turner'),
	   ('William Simmons'),
	   ('Donald Rodriguez'),
	   ('Hazel Garcia'),
	   ('Linda Smith');
	  
create table monthly_salary(
	id serial primary key,
	monthly_salary int not null
);

select * from monthly_salary


insert into monthly_salary (monthly_salary)
values (1000),
       (1100),
       (1200),
       (1300),
       (1400),
       (1500),
       (1600),
       (1700),
       (1800),
       (1900),
       (2000),
       (2100),
       (2200),
       (2300),
       (2400),
       (2500);